spring:
  datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/SEPEL-ai
      username: sepel
      password: sepel
      initialization-mode: always
      auto-commit: false
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  elasticsearch:
      uris: http://localhost:9200
      username: elastic
      password: J_TbUCWLthMd1F*-XToM
      
---

logging:
  file:
    name: ai.log
  pattern:
      console: "%d{HH:mm:ss} %-5level [%thread]: %msg %n"
      file: "%d{HH:mm:ss} %-5level [%thread]: %msg %n"
  level:
    .: info
    org.springframework.web: ERROR
    org.apache.shiro: DEBUG


server:
 error:
     whitelabel:
         enabled: false
 tomcat:
   max-http-form-post-size: 2000000000
   max-swallow-size: 2000000000

---

mybatis:
  mapper-locations: classpath:maps/*.xml
